apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cased-agent.fullname" . }}
  labels:
    {{- include "cased-agent.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes", "namespaces", "events"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods", "nodes"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cased-agent.fullname" . }}
  labels:
    {{- include "cased-agent.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cased-agent.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "cased-agent.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
