apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cased-agent.fullname" . }}
  labels:
    {{- include "cased-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-key: {{ required "apiKey is required" .Values.apiKey | quote }}
